### ISSUE TITLE
Always show front cam

### ISSUE THREAD

**Issue by wandonye** [oney/react-native-webrtc#164]
I'm using the code below to get the local camera stream. Even I set the source to be back manually, it still shows front. 

```
getLocalStream(isFront, callback) {
  MediaStreamTrack.getSources(sourceInfos => {
    let videoSourceId;
    console.warn(isFront ? "front" : "back");
    console.log('source list', sourceInfos);
    for (const i = 0; i < sourceInfos.length; i++) {
      const sourceInfo = sourceInfos[i];
      if(sourceInfo.kind == "video" && sourceInfo.facing == "back") {
        videoSourceId = sourceInfo.id;
      }
    }
    getUserMedia({
      audio: true,
      video: {
        // facingMode: isFront ? 'user' : 'environment',
        optional: [{sourceId: videoSourceId}],
        mandatory: { minWidth: 800, minHeight: 600 },
        width: { min: 800, ideal: 1280 },
        height: { min: 600, ideal: 1024 }
      }
      // "audio": true,
      // "video": {
      //   optional: [{sourceId: videoSourceId}]
      // }
    }, function (stream) {
      callback(stream);
    }, console.warn);
  });
}
```

**Comment by wandonye** [comment]
The callback function has the release codes:

```
setSelfViewSrc(stream) {
    if (this.localStream) {
      //remove from remote
      this.localStream.release();
    }
    console.warn(stream);
    this.localStream = stream;
}
```

**Comment by zxcpoiu** [comment]
fixed in:
https://github.com/oney/RCTWebRTCDemo/commit/3916930150c61bf2efc3523c223846f8004386ee

try adding facingMode as well
see: https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L51

**Comment by lmbao** [comment]
I added that line to my code but it still not working: it only shows front camera...

**Comment by zxcpoiu** [comment]
is it works if you run demo app on the same device?

be sure to add these line in your code. or, refine your code based on latest demo

https://github.com/oney/RCTWebRTCDemo/blob/master/main.js#L39-L41

**Comment by lmbao** [comment]
@zxcpoiu Yes I already had those lines in my code. Also I am not able to test the demo because by simply doing `npm install` and then running the project on Xcode gives me to many errors that I was not able to fix

**Comment by wandonye** [comment]
I tracked into the package in XCode and found that it was this line
```optional: [{sourceId: videoSourceId}],```
preventing me from getting the back camera.

If I have this line, `videoDevice` turns out to be the audio, and `videoDevice.position` in `WebRTCModule+RTCMediaStream.m` has no value and thus skip the entire block:
```
    switch (videoDevice.position) {
    case AVCaptureDevicePositionBack:
      if (videoSource.canUseBackCamera) {
        videoSource.useBackCamera = YES;
      }
      break;
    case AVCaptureDevicePositionFront:
      videoSource.useBackCamera = NO;
      break;
    }
```
Not sure if this is intentional. But it might be helpful to mention in the document.

**Comment by zxcpoiu** [comment]
I believe it is a bug in javascript.

`sourceInfos.id` should be `videoSourceId`

but I'm not sure if it still needs `optional` options and what the content should be.
( I'm not using video  )

please check if it works by changing this line:
`optional: [{ sourceId: sourceInfos.id }]`
to 
`optional: (videoSourceId ? [{ sourceId: videoSourceId}] : [])`

**Comment by lmbao** [comment]
@zxcpoiu I changed that line but it is still not working

**Comment by zxcpoiu** [comment]
can you post your final snippets like @wandonye did?
and it's ios or android.

btw, please check the latest demo IN THE PR https://github.com/oney/RCTWebRTCDemo/pull/39
