### ISSUE TITLE
Non-public API usage

### ISSUE THREAD

**Issue by siemya** [oney/react-native-webrtc#223]
hey @oney 

When i submit my app to appstore, it gets denied with the error;

> The app references non-public selectors in yourApp: channelId, initWithURLStrings:, isBinary, reportId, sdp, sendData:, setChannelId:, stringForType:, typeForString:

When i search my project, it looks like webrtc is using them.

**Comment by siemya** [comment]
did anyone succeeded to submit an app to appstore?

**Comment by saghul** [comment]
Yes, we have succeeded: https://itunes.apple.com/us/app/jitsi-meet/id1165103905?mt=8

I wasn't the one submitting the build, but I'm not aware of such problems.

**Comment by antoniotuzzi** [comment]
this is webrtc/chromium bug 6382 https://bugs.chromium.org/p/webrtc/issues/detail?id=6382#c19
has been solved in M58

**Comment by siemya** [comment]
hey @antoniotuzzi,

when i search the project in github, those keywords still appear.

**Comment by siemya** [comment]
@saghul interesting.

does your react-native-webrtc module contain those keywords?

**Comment by antoniotuzzi** [comment]
I'm quite sure that webrtc build after feb 8 2017 are ok

**Comment by saghul** [comment]
We use current master, so M54.


-Saúl

**Comment by siemya** [comment]
@saghul @antoniotuzzi 

the main problem is we are using react version 0.39.2 atm and we are not ready to upgrade.

thats why we are using version 0.54.4 :/

**Comment by saghul** [comment]
You can probably take master, fix up imports and make it work with RN < 0.40, basically undoing what was done to upgrade, it shouldn't be a huge effort.


-Saúl

**Comment by shaneneuerburg** [comment]
We are still running into a similar issue as this. The error back from Apple is:

> Non-public API usage:
> 
> The app references non-public selectors in relianceconnect: addStream:, channelId, initWithURLStrings:, isBinary, sdp, sendData:, setChannelId:, setIsEnabled:, stringForType:

In the comment above (https://github.com/oney/react-native-webrtc/issues/223#issuecomment-286428269), it doesn't look like the WebRTC library changes actually fixed this particular issue but a different one.

**Comment by harish50** [comment]
+1

**Comment by saghul** [comment]
Just submitted a build to Apple last week with no issues. Tell them those symbols are way too generic or to point out the offending framework.

**Comment by harish50** [comment]
> Just submitted a build to Apple last week with no issues. Tell them those symbols are way too generic or to point out the offending framework.

This is what I got from Apple.

Thank you for contacting the App Store Review Team.To pass through review we require that apps make use of only public and documented APIs. If this app, or a library which it includes, make use of non-public APIs it will continue to be rejected until those APIs are removed. No exceptions to the 2.5.1 guideline requirement will be provided at this time.

**Comment by saghul** [comment]
I don't know what to tell you. Those symbols are not private and I haven't gotten any problems because of them.
