### ISSUE TITLE
EXC_BAD_ACCESS occasionally when reloading app

### ISSUE THREAD

**Issue by briank621** [oney/react-native-webrtc#431]
Every once in a while, when I reload my application the whole program will crash with the following message:  `Thread 1: EXC_BAD_ACCESS`. 

The file with the issue is RTCVideoViewManager.m, and on the call stack, I see RTCVideoTrack dealloc and RTCVideoView.cxx_destruct.

![screen shot 2018-03-20 at 4 26 04 pm 2](https://user-images.githubusercontent.com/9010681/37680853-7e0061e0-2c5b-11e8-9b71-20926f1c6662.png)

This issue forces me to restart the whole app from XCode instead of just reloading.

In the React Native Debugger, I see the following message:

`Invalidating <RCTCxxBridge: 0x1c05b7300> (parent: <RCTBridge: 0x1c42a4680>, executor: RCTWebSocketExecutor)`

**Comment by zxcpoiu** [comment]
please refers to:

https://github.com/oney/react-native-webrtc/issues/403#issuecomment-355933392
https://github.com/oney/react-native-webrtc/issues/386#issuecomment-352701183

We couldn't find any way to around it currently.

If anyone knows, please share it here with love :+1:

**Comment by saghul** [comment]
Please try with the latest release, I haven't seen this happen for ages now, I hope we fixed it!

**Comment by remigijusbalc** [comment]
Still facing this issue on react native 0.57.0, any suggest how to fix it?
