### ISSUE TITLE
Execution failed for task ':WebRTCModule:compileReleaseJavaWithJavac'

### ISSUE THREAD

**Issue by shaheem-khanzada** [oney/react-native-webrtc#499]
#### Platform information

* **React Native version**:
0.54.2

**Comment by 8BallBomBom** [comment]
Did you enable Java 8 Support?
https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

**Comment by Proxy08** [comment]
Same problem here, I've tried to create a new webrtc project I got this issue today. it used to work fine though on window. I don't  know if it is beause I'm using a mac

**Comment by Proxy08** [comment]
I've just tried on my windows I got this issue too
tive-webrtc\android\src\main\java\com\oney\WebRTCModule\WebRTCModule.java:46: error: cannot find symbol
        ThreadUtils.runOnExecutor(() -> initAsync());
                                  ^
  symbol:   method metafactory(Lookup,String,MethodType,MethodType,MethodHandle,MethodType)
  location: interface LambdaMetafactory
Fatal Error: Unable to find method metafactory
:react-native-webrtc:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by shaheem-khanzada** [comment]
@8BallBomBom yes I enabledthe java 8 support

**Comment by shaheem-khanzada** [comment]
@Proxy08 I also got the same issue when I run it in another laptop

**Comment by 8BallBomBom** [comment]
Have you tried doing a clean build?
Also my build settings.

compileSdkVersion 27
buildToolsVersion "27.0.3"
minSdkVersion 19
targetSdkVersion 22
gradleBuildTools 3.1.3
gradle 4.4

**Comment by shaheem-khanzada** [comment]
@8BallBomBom which version of react-native and webrtc ur using

**Comment by 8BallBomBom** [comment]
RN 0.55.4 and WebRTC 1.67.0

**Comment by shaheem-khanzada** [comment]
@8BallBomBom its working fine before but now when I delete node module and reinstall it again it throws error

**Comment by shaheem-khanzada** [comment]
@8BallBomBom can u try it again uninstall it and then install it again and then try?

**Comment by 8BallBomBom** [comment]
I have already binned my node folder, re-updated via yarn.
Have you tried upping RN? 0.55.4 is pretty stable, not sure about 0.56 as of yet, has a lot of breaking issues.

**Comment by shaheem-khanzada** [comment]
@8BallBomBom how u use compileOption ?

**Comment by 8BallBomBom** [comment]
Heres my build.gradle file.
https://files.bombom.uk/index.php/s/w4nEcLWWrg3WfPx

**Comment by shaheem-khanzada** [comment]
@8BallBomBom u use implementation not compile why is that so ? and may u also send me android/build.gradle  file

**Comment by 8BallBomBom** [comment]
Updated gradle version complains about compile being deprecated by the end of this year.
So you have to change things over to use implementation instead.

**Comment by shaheem-khanzada** [comment]
@8BallBomBom it works thanks man you solved my problem

**Comment by RnbWd** [comment]
I've got the same issue

**Comment by 8BallBomBom** [comment]
@RnbWd If you upgrade gradle and react native to at least 0.55.4. 
Does the issue still exist?
Hopefully the build configs help.

**Comment by RnbWd** [comment]
I've upgraded my gradle version and I'm using the latest version of react, however, i reverted to the previous release 1.63.0 and it works fine, I'll update this thread if I try to upgrade again. My compilation issue might have something to do with Java 8

**Comment by saghul** [comment]
@RnbWd Yes, Java 8 must be enabled: https://github.com/oney/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

**Comment by ricardonoguti** [comment]
I have the same problem, can anyone help me? I am trying to install in version 0.54.3. But whenever I configure the android, the error always occurs. Can someone help me?

**Comment by jessk77** [comment]
@8BallBomBom I follow your steps and now I'm getting this message

> The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.

Somebody knows why? :(

**Comment by jessk77** [comment]
@8BallBomBom yes I did

**Comment by 8BallBomBom** [comment]
Have you gone though, updated gradle, build tool versions, clean build?
If so everything should be working.

**Comment by hakiimmislam** [comment]
Im still having the same issue. Already followed the installation guide. Is there any way to solve it? My react native version is 0.55.4.

**Comment by saghul** [comment]
We just updated the instructions, please check and try again.

**Comment by akem3g** [comment]
@saghul thanks. I can build successfully but it also shows a few things. First, based on your documentation I need to put `'='` between `compileSdkVersion` and `27` and same as `buildToolsVersion`. Second, when I use `classpath 'com.android.tools.build:gradle:3.0.1'` from your documentation, it gives a warning `Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.` Just want to let you know maybe you have any ideas what is happening. Other than that my issue is solved. Thanks!

**Comment by anagar23** [comment]
It failed for me on `classpath 'com.android.tools.build:gradle:2.3.3'` Gradle version. De you have any workaround for it. I don't want to upgrade my build version.
